[project]
name = "django_api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.1",
    "ipython>=9.6.0",
    "python-dotenv>=1.1.1",
]
