apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: meu-secret-k8s
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef: # Referência da SecretStore que contem os dados para conectar na AWS
    name: aws-secret-store
    kind: SecretStore
  target: # A Secret k8s que será criada
    name: app-secret-k8s
    creationPolicy: Owner
  data:
    - secretKey: codigo # nome da chave que será criada na Secret app-secret-k8s
      remoteRef:
        key: meu-secret-na-aws
        property: codigo
    - secretKey: senha # nome da chave que será criada na Secret app-secret-k8s
      remoteRef:
        key: meu-secret-na-aws
        property: senha