apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-nfs-volume
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany # Permite que esse volume seja montado em mais de um nó
    #- ReadWriteOnce # Permite montar em apenas um único nó --padrão
    #- ReadOnlyMany # Pemite apenas leitura e volume pode ser montado em mais de um nó.
  nfs:
    path: /storage
    server: 192.168.0.197
    