apiVersion: v1
kind: Service
metadata: 
  name: nginx-service
spec:
  # type: ClusterIP # Usado para acesso dentro do cluster, cria um IP est치vel e um nome DNS interno.
  type: NodePort
  selector:
    app: mydeploy
  ports: 
    - protocol: TCP
      port: 8008 # Porta que o Service vai expor internamente (ClusterIP)
      targetPort: 80 # Porta que o container escuta (definida l치 no Pod)
      nodePort: 30080 # Porta que ser치 exposta no n칩